### PR TITLE
Simplify the implementation of the crate and fix #1 at the same time.

### LINKED ISSUE #1: Compile failure if the crate using the `wasm_init!` macro does not itself depend on wasm_bindgen.
I don't know how to solve this, but the `#[wasm_bindgen]` proc macro does not appear to support renaming the `wasm_bindgen` crate to something else, and refers to the module path `wasm_bindgen` in the expanded output. This causes `wasm_init!` to not compile if the caller does not itself depend on wasm_bindgen.

I implemented a replacement for the `inventory` crate using `ctor` and `wasm-init`. Calling `inventory::submit!` without depending on `wasm_bindgen` produces get the following output:

```
error[E0433]: failed to resolve: use of undeclared crate or module `wasm_bindgen`
  --> src/core/src/scripting/globals.rs:39:1
   |
39 | / inventory::submit!(GlobalLib::new("serde global markers", |ctx| {
40 | |     scripting::serde::global_markers(ctx);
41 | |     Ok(())
42 | | }));
   | |___^ use of undeclared crate or module `wasm_bindgen`
   |
   = note: this error originates in the attribute macro `$crate::__macrodeps::wasm_bindgen` which comes from the expansion of the macro `inventory::submit` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find value `FUNCTION` in this scope
  --> src/core/src/scripting/globals.rs:39:1
   |
39 | / inventory::submit!(GlobalLib::new("serde global markers", |ctx| {
40 | |     scripting::serde::global_markers(ctx);
41 | |     Ok(())
42 | | }));
   | |___^ not found in this scope
   |
   = note: this error originates in the attribute macro `$crate::__macrodeps::wasm_bindgen` which comes from the expansion of the macro `inventory::submit` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `WasmDescribe` in this scope
  --> src/core/src/scripting/globals.rs:39:1
   |
39 | / inventory::submit!(GlobalLib::new("serde global markers", |ctx| {
40 | |     scripting::serde::global_markers(ctx);
41 | |     Ok(())
42 | | }));
   | |___^ not found in this scope
   |
   = note: this error originates in the attribute macro `$crate::__macrodeps::wasm_bindgen` which comes from the expansion of the macro `inventory::submit` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `inform` in this scope
  --> src/core/src/scripting/globals.rs:39:1
   |
39 | / inventory::submit!(GlobalLib::new("serde global markers", |ctx| {
40 | |     scripting::serde::global_markers(ctx);
41 | |     Ok(())
42 | | }));
   | |___^ not found in this scope
   |
   = note: this error originates in the attribute macro `$crate::__macrodeps::wasm_bindgen` which comes from the expansion of the macro `inventory::submit` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by kyren**
Drops the `paste` crate and does not bother to use `#[wasm_bindgen]` to generate the exported init function. Instead, exports a plain `extern "C"` function and uses uses `#[export = name]` to set its name, as `wasm-bindgen` would have done.

This is both simpler, and also does not require that the calling crate have `wasm_bindgen` as a direct dependency, so it fixes #1 at the same time.

### CODE REVIEW

File: wasm-init/src/wasm.rs [hunk 1]
```diff
@@ -50,12 +49,15 @@ pub fn wasm_init() {
...
 	($gensym:ident, $($input:tt)*) => {
-		$crate::__macrodeps::item! {
-			#[$crate::__macrodeps::wasm_bindgen]
-			pub fn [<__wasm_init $gensym>]() {
+		const _: () = {
+			#[export_name = $crate::__macrodeps::concat!(
+				"__wasm_init",
+				$crate::__macrodeps::stringify!($gensym)
+			)]
+			pub unsafe extern "C" fn init() {
```
Comment (returnString) [inline wasm-init/src/wasm.rs]: Does this need to be unsafe?

**Review by returnString — COMMENTED** [review]
Great catch! I've been thinking about the best way of structuring some test cases for this crate and "crate that doesn't depend on wasm_bindgen itself" is definitely going on the list now.

Left one comment re: unsafe but otherwise looks great, and removing deps is always a win. Thanks for this 😊

File: wasm-init/src/wasm.rs (hunk 1 above)
Comment (kyren) [reply wasm-init/src/wasm.rs]: I honestly have no idea. I assume no, but all exports are generated that way from wasm-bindgen? The only reason it was there was because I started with what wasm-bindgen was generating. Nobody is even able to touch the function without going through wasm lookup from javascript so.. the `unsafe` has no effect anyway so I'll remove it, it just serves to confuse.

**Comment by returnString** [comment]
Unsafe comment makes sense, I was only worried about inadvertently providing an unsafe context for the user code in the macro invocation.

Thanks for flagging this up and fixing so quickly 😊

**Comment by kyren** [comment]
> Unsafe comment makes sense, I was only worried about inadvertently providing an unsafe context for the user code in the macro invocation.
> 
> Thanks for flagging this up and fixing so quickly 😊

Oh you're right, I didn't even think about that, I *constantly* forget that unsafe functions provide an implicit unsafe body, good catch!

Also thanks for the quick release! ❤️

**Comment by returnString** [comment]
Yeah it's a weird one! And no worries, thanks for the straightforward report and patch 😊
